/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_emp_utils_DracoHelper */

#ifndef _Included_org_emp_utils_DracoHelper
#define _Included_org_emp_utils_DracoHelper
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     org_emp_utils_DracoHelper
 * Method:    encode
 * Signature: ([FII)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_emp_utils_DracoHelper_encode
  (JNIEnv *, jobject, jfloatArray, jint, jint);

/*
 * Class:     org_emp_utils_DracoHelper
 * Method:    decode
 * Signature: ([B)[F
 */
JNIEXPORT jfloatArray JNICALL Java_org_emp_utils_DracoHelper_decode
  (JNIEnv *, jobject, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
